apiVersion: v1
kind: Service
metadata:
  name: CourseRegistrationSystem
  labels:
    app: CourseRegistrationSystem
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CourseRegistrationSystem